version: '3.8' # Utilisez une version récente de la spécification Compose

services:
  # --- Service DNSCrypt-Proxy ---
  dnscrypt-proxy:
    # Vous pouvez utiliser une image pré-construite populaire ou construire la vôtre.
    # klutchell/dnscrypt-proxy est une image communautaire souvent utilisée.
    image: klutchell/dnscrypt-proxy:latest
    container_name: dnscrypt # Nom pratique pour le conteneur
    restart: unless-stopped # Redémarre automatiquement sauf si arrêté manuellement
    volumes:
      # Montez votre fichier de configuration local dans le conteneur.
      # Le chemin /config est souvent utilisé par l'image klutchell. Vérifiez la doc de l'image si vous en utilisez une autre.
      - ./dnscrypt-proxy.toml:/config/dnscrypt-proxy.toml:ro # 'ro' = read-only (lecture seule)
      # Optionnel : Montez un volume pour le cache de dnscrypt si activé dans votre config
      # - dnscrypt_cache:/var/cache/dnscrypt-proxy
    # Pas besoin d'exposer de ports sur l'hôte pour dnscrypt-proxy,
    # car seul AdGuard (dans le même réseau Docker) a besoin de le joindre.
    # Assurez-vous que dnscrypt-proxy écoute sur une IP interne (ex: 0.0.0.0:5353) dans son fichier de config.
    networks:
      - dns-network # Attache le service à notre réseau défini plus bas

  # --- Service AdGuard Home ---
  adguardhome:
    # Utilise l'image officielle AdGuard Home
    image: adguard/adguardhome:latest
    container_name: adguard # Nom pratique pour le conteneur
    restart: unless-stopped # Redémarre automatiquement
    ports:
      # Port DNS standard (TCP et UDP) exposé sur votre machine hôte
      - "53:53/tcp"
      - "53:53/udp"
      # Port pour l'interface web d'AdGuard (accessible via http://<votre-ip>:3000)
      - "3000:3000/tcp"
      # --- Ports Optionnels ---
      # Décommentez si vous configurez AdGuard pour DoT (DNS over TLS)
      # - "853:853/tcp"
      # Décommentez si vous configurez AdGuard pour DoH (DNS over HTTPS) - Attention aux conflits si un serveur web tourne sur 443
      # - "443:443/tcp"
      # - "443:443/udp" # Pour HTTP/3 (QUIC) si supporté et activé
      # Port pour l'interface web sécurisée (si configurée)
      # - "8443:8443/tcp" # Exemple de port alternatif pour HTTPS UI
      # Port DHCP (si vous activez le serveur DHCP d'AdGuard - nécessite --net=host ou des privilèges spéciaux)
      # - "67:67/udp"
      # - "68:68/tcp"
      # - "68:68/udp"
    volumes:
      # Stockage persistant pour les données de travail d'AdGuard (logs, stats, etc.)
      - ./adguard_work:/opt/adguardhome/work
      # Stockage persistant pour la configuration d'AdGuard
      - ./adguard_conf:/opt/adguardhome/conf
    # Dépendance : S'assure que dnscrypt-proxy est démarré avant AdGuard
    depends_on:
      - dnscrypt-proxy
    networks:
      - dns-network # Attache le service à notre réseau défini plus bas

# --- Définition des Réseaux ---
networks:
  dns-network: # Nom du réseau interne utilisé par les conteneurs pour communiquer
    driver: bridge # Type de réseau par défaut, suffisant ici

# --- Définition des Volumes (Optionnel si vous utilisez les chemins locaux comme ci-dessus) ---
# volumes:
#   dnscrypt_cache: # Si vous avez activé le volume de cache pour dnscrypt
#   adguard_work:
#   adguard_conf: